# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Realestate' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Realestate
#  pod 'Firebase/Analytics'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  
  target 'Realestate-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'react-native-maps', :path => '../node_modules/react-native-maps'

    pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'

  end

  target 'RealestateTests' do
    inherit! :search_paths
    # Pods for testing
  end

end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    #    if target.name == 'react-native-google-maps'
    #      target.build_configurations.each do |config|
    #        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
    #      end
    #    end
    
    if target.name == "React"
      target.remove_from_project
      else
      target.build_configurations.each do |config|
#        config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
        #        if swift4.include?(target.name)
        #          config.build_settings['SWIFT_VERSION'] = '4.2'
        #        end
      end
    end
  end
end
